const fs = require('fs');                                                                                                                                                                                                                     
const path = require('path');                                                                                                                                                                                                                 
                                                                                                                                                                                                                                              
const cb = (err, data) => {                                                                                                                                                                                                                   
  console.log("readdir just finished");                                                                                                                                                                                                       
  if (err) {                                                                                                                                                                                                                                  
    console.error(err);                                                                                                                                                                                                                       
    process.exit(1)                                                                                                                                                                                                                           
  }                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
  console.log(data);                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
// we pass in a callback function                                                                                                                                                                                                             
fs.readdir('./', cb);                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
// we do the same call, except with an anonymous function                                                                                                                                                                                     
fs.readdir('./', (err, data) => {                                                                                                                                                                                                                
  console.log("readdir 2 just finished");                                                                                                                                                                                                     
  if (err) {                                                                                                                                                                                                                                  
    console.error(err);                                                                                                                                                                                                                       
    process.exit(2);                                                                                                                                                                                                                          
  }                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
  console.log(data);                                                                                                                                                                                                                          
});                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
// we don't have access to the data variable out here                                                                                                                                                                                         
// after the readdir call is queued, we'll console.log                                                                                                                                                                                        
console.log("readdir hasn't finished yet");                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
// the program won't exit though until all callbacks have finished  
